name: Add issue to UnivAI project

on:
  issues:
    types: [opened, reopened, transferred, labeled]

permissions:
  contents: read
  issues: read

jobs:
  add-to-project:
    if: ${{ !contains(github.event.issue.labels.*.name, 'note') }}
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@5afcf98fcd03f1c2f92c3c83f58ae24323cc57fd # v2.0.0
        with:
          project-url: ${{ vars.UNIVAI_PROJECT_URL }}
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
